### ISSUE TITLE
Demo support?

### ISSUE THREAD

**Issue by neuromancer** [klei1984/max#2] opened 2020-02-14 15:46 UTC
It looks like there is an [M.A.X demo](https://archive.org/details/M.A.X.MechanizedAssaultandExploration_1020) that can be freely (and probably legally) downloaded to test this port. Is there any plans to support it?

**Comment by klei1984** [comment] 2020-02-15 06:48
I made a quick test with that demo package on windows 10 with the latest binary.
The game actually started up and I entered into a custom game against a single CPU enemy.
I am not saying that missing or changed resources in max.res would not create problems later during game play, but the port could be tried out at least.
If you have problems building from source code I could upload a windows and linux executable for you to test.

**Comment by klei1984** [comment] 2020-02-15 11:10
The v1.03a interactive demo's max.res file contains 1065 resources. 2 of these are related to demo advertisement and are not present in v1.04. There is but a single resource, HELP_ENG, which is different in the two versions. And finally there are 764 resources missing from the demo not counting actual FLC animations and audio files.
Resources not available do not crash the game in general. Instead they will not be rendered or played. E.g. the Mobile Anti Aircraft unit's sprite is not available so it will be invisible even though the unit can be selected and by enabling Hits visibility in the GUI invisible units can be found.
I made a short video to demonstrate this which you can find on the home page. Direct link to news entry: https://klei1984.github.io/max/2020/02/15/Messing-around-with-demo-versions-of-MAX.html

Directly supporting the demo versions of the game, realizing 1:1 functional behavior, would be difficult in the sense that the demo versions' implementation considerably differ from the v1.04 version. But to be able to use the port with at least one of the demo versions for play testing is possible already.

**Closed** 2020-02-16 07:13 UTC
Labels: question

**Comment by neuromancer** [comment] 2020-02-16 12:25
Neat, it's amazing that you produced an entire blog post to answer this! Perhaps it could be interesting to make a entire list of the different demos and which one could be supported (and the limitations).

**Comment by klei1984** [comment] 2020-02-17 18:27
I intend to analyze deeper what debugging features are built into the various versions of the game if I cannot activate the network based debug mode for v1.04.
But spending much time on the various demo versions does not make much sense. The full game is as cheap as a hamburger during sales and all unreleased, unfinished contents are also present in the final version. I intend to create an article on the cancelled and repurposed units soon. I already activated those units in game once; you can click on and check out the statistics of the alien derelict buildings.

E.g. in v1.04 we can find the monopole mine which did not make into the game at the end and was actually a shield generator initially by design and finally became an alien derelict or the communications tower which became the gold refinery, the recreation center and life support plants that became again alien derelicts, the master builder which can be seen in one of the in-game videos but never made it into the actual game, etc. Only a handful of art and in-game graphic sprites were modified since the v1.00 demo so there is really not much added value.
