### ISSUE TITLE
[Bug] fade to black when pressing the files button to save

### ISSUE THREAD

**Issue by goofyseeker311** [klei1984/max#23] opened 2023-03-15 19:38 UTC
### Operating System

Windows

### Source of bug?

- [ ] Original M.A.X. v1.04
- [x] M.A.X. Port

### M.A.X. Port Version

website github.io

### M.A.X. and DOS or DOSBox Versions

native msys32 build

### What is the issue you encountered?

your main github.io page does not link to the actual download repo (this)

**Comment by goofyseeker311** [comment] 2023-03-15 20:45
also the build process does not install automatically, and if you use the protected program files/max directory then the program cannot save settings or games (write assert error). also arrow keys to scroll the display would be nice, simple ui enhancement.

**Comment by klei1984** [comment] 2023-03-15 22:38
Hello @goofyseeker311 ,

> your main github.io page does not link to the actual download repo (this)

I will add a dedicated download menu item and related page to the homepage as soon as I attempt to make a "stable" release build. As of today master branch builds are still unstable unfortunately and phase out way too fast. I follow the home page design of Jagged Alliance 2 - Stracciatella. See here: https://ja2-stracciatella.github.io/download/ . Please note that there will be no nightly builds for M.A.X. Port until the first release is made. Nightly builds will be provided for regression testing purposes only.

> also the build process does not install automatically (mingw32), and if you use the protected program files/max directory then the program cannot save settings or games

As of today M.A.X. Port is a patch that is supposed to be installed into the original M.A.X. game folder as suggested by the readme.md. Installing the patch into the steam, gog.com, egs, and similar M.A.X. game folders guarantees you write access.

- I agree with you that it is not fortunate that the NSIS installer uses the install prefix and package name as default path as that is useless.
- I agree with you that the configured install prefix is basically useless as the install path should point to the M.A.X. install folder.
- I agree with you that not using the NSIS installer generated by cpack on demand, instead calling makefile install target to copy stuff into the program files folder is useless as MS Windows does not work like that and this is why the NSIS installer is provided in the first place.

It is not planned to develop OS specific scripts to hunt down the existing installation locations of M.A.X. copies. I will extend the build instructions article, https://klei1984.github.io/max/build/ , on the home page to inform users that they are supposed to run cpack after build to generate the deb or NSIS installers and that users are supposed to install the patch into their previous M.A.X. installation locations.

> arrow keys to pan the display and mouse wheel to zoom would be nice, simple ui enhancement.

M.A.X. Port simulates the original M.A.X. architecture. W.r.t. keyboard and mouse input this means that only MS-DOS DPMI server services are simulated currently. In case of mouse input this means 3 buttons and x,y position. In case of keyboard this means US standard keyboard layout which is simulated by SDL USB key and scan code 1:1 translation look up tables.

All this means that adding mouse wheel to UI controls and to the in-game tactical map is not a simple matter.

Arrow keys do work as per USB key and scan code rules. See evidence here: https://youtu.be/EwZb10FiTdc?t=37 . I agree with you that the game should be able to recognize multiple variants of USB scan and key codes representing arrow keys combined with modifiers like Num Lock. This is not the case unfortunately. There is a 1:1 mapping between DPMI server scan codes to USB ones. On my laptop I have to disable the num lock modifier to get working arrow keys.

Work package 7, https://klei1984.github.io/max/roadmap/ , is planned to add support for DPI aware Unicode true type fonts rendering, proper support for keyboard locales and customization of key bindings. Prerequisite for all of these is the complete refactoring of GNW library modules. Step by step work break down looks something like this:
- develop unicode true type fonts (outlines, bitmaps, vectors, minimum 3 em sizes, etc).
- develop new GNW font manager, compliant with the GNW Font Manager API, that supports true type fonts and UTF8/UCS32 conversions and rendering with various outline, underline, etc. effects.
- externalize all text and store them in utf8 encoded configuration files.
- replace GNW's MS-DOS human machine interface modules to support modern mouse and keyboard features and OS and language dependent locales.
- modify the game specific UI control classes to manage locale aware hot keys based on control expressions populated via language files and generic mouse inputs including of course the mouse wheel.
- modify the game specific UI control classes to fill text labels, boxes and edit boxes based on available space and DPI / em size constraints.
- rewrite all c++ game specific GUI modules to integrate with all the above feature changes.

Design alternative to all of these: replace GNW with imgui + sdl2 or imgui + glfw + openal.


I hope that the above summary of WP 7 and the planned release procedures answer all your concerns. If so, please feel free to close the defect report.

**Comment by goofyseeker311** [comment] 2023-03-16 15:54
yes great.

one/two more issues:
1) I had to manually copy all the dlls from the msys64 (msys32) to get the windows .exe running in the writable folder
2) when recording with obs, the start menu image when clicked only changes to the cursor pixel, not full image, even if the image shows on the screen to be fully changed to the next image

**Comment by goofyseeker311** [comment] 2023-03-16 16:52
and one more: at turn 32, when clicking the files button, to save, the screen faded to black, then was bugged, then came back in like several seconds

**Comment by klei1984** [comment] 2023-03-17 02:40
Too many issues, difficult to track them this way :)

1) The SDL2 DLLs and any other runnables are normally registered by msys2 on install so that they are found in the system path. At least on my computer where I have msys2 I never had problems with locating the DLLs. If you run the cpack command from the build folder it creates an NSIS installer for Window that also installs all dependencies (10 DLLs). I will try to figure out whether cmake itself could configure the gnu make install command to copy the same dependencies. I never use the install command on Windows, never tried.

2) This is a defect in the original game. It is documented as defect 146 on this page: https://klei1984.github.io/max/defects/ . The problem is that the game's internal draw back buffer is not double buffered... to fix this a more sophisticated architectural change would be required. This defect is not in focus for now.

3) 16:9 and any aspect ratio where width > height is already supported. Higher resolutions are also supported (except text rendering due to complexity which is planned to be handled in WP 7). This blog entry describes how to configure the game to run in 16:9 Full HD mode and there is a demonstration video as well: https://klei1984.github.io/max/2023/03/13/Full-hd-game-play.html .

 The original tactical map or tile map renderer of M.A.X. was written in pure assembler and was using a heavily optimized integer logic algorithm that is insanely efficient, but has severe design constraints at the same time. E.g. maps can only take the shape of squares, rectangles are no go. Map tiles can only be 64x64 or 32x32 pixels and the tile buffer must build a metadata database in the right format to be able to reference the correct data and copy it to the right screen back buffer offsets. The algorithm basically can translate the tile map buffer to screen back buffer positions and at the very same step perform nearest neighbor rescaling of tiles.
 I was able to rewrite the original assembler algorithm using pure ISO C, but that does not mean that I fully understand what it does... quite the opposite, I do not understand most of it and as long as I cannot figure it out completely it will not be possible to zoom out the tactical map to such levels where the tactical map is not fully occupying the available square space on the screen.
 In M.A.X. 2 the renderer was improved that the tactical map can be rendered in such a way that it does not fully occupy the aforementioned square area... similarly to the way Supreme Commander renders the map in zoomed out state. This feature should be surely back ported from M.A.X. 2 at some point.
 To be honest, best would be to ditch the software renderer and move to OpenGL 3.x or Vulkan.

4) I also experienced the extreme slowdowns. It does not only happen when you go to the save/load menu which fades out and in the screen. I am unable to consistently reproduce the issue. When the issue is present, call / function trace does not change. Profiler data from gpof did not help to figure out what is slowing down to a crawl either. At some point I was sure that the issue occurs within SDL2 itself. That would explain why I do not see any slowdown in use code via gnu profiler or call trace. At some point I even went and wrote two screen blitter implementations. You can switch between the two implementations in svga.c by setting SVGA_NO_TEXTURE_UPDATE to true or false. It is realized as a compilation time switch which cannot be toggled at run-time. If the issue is not related to SDL2 or the way I am using the SDL2 APIs, than it could happen that the video card driver clashes or enters into temporary soft lock... we will not know until the root cause is found. As of now, I am at a pickle... The first step is definitely a way to reliable trigger the error. But I did not find a reliable method so far.

5) There is another hard to reproduce issue which causes the simulated MS-DOS system timer to go haywire. This manifests e.g. in the super fast floating brain anomaly or the always immediately restarting main menu attract demo (the demo fight you referred to) regardless that you want to exit from it once and for all. The original game and its game engine did not support PC low power modes. The game creates a lot of so called software timers. E.g. a feature saves a time stamp and starts to poll for the time to see how much time has elapsed. The time stamp is taken from the system timer. In case the PC is put to sleep the timer will jump and the software timer based timings will all go haywire. In multiplayer this is instant guaranteed desyc. In other cases simply the AI will skip some turns forward as its time allowance for "thinking" elapses... I could not figure out so far what could cause the timer to skip and time stamp references not to update... finding a reliable way to reproduce the issue is again the first step which is still pending.

6) airplanes have a very simple go straight from X to Y movement. Positions of the unit sprites to render are based on x,y pixel coordinates instead of 64x64 tactical map grid cell coordinates. Group movement limits the group velocity. Velocity of a unit is related to the game tick periods not to the actual system timer elapsed time directly. I cannot fathom what could cause one unit in the group to count down speed points based on velocity while the other does nothing. There is a way actually to make infinite movement. It is documented on the defects page as defect 136. Maybe you observed this issue. Although... I was only able to induce this for the entire group of units, not just one alone. Maybe it has to do something with the frame ticker and the system timer even though I said that those should not be related.

Maybe 4,5 and 6 are all caused by the exact same root cause. But i Have no clue what could be this cause :/

**Comment by goofyseeker311** [comment] 2023-03-17 11:11
2. but the screen (in OBS) updates only after moving a mouse? what? :)

**Comment by klei1984** [comment] 2023-03-17 17:09
Hello @goofyseeker311 , did you minimize the game window by chance? I found an issue related to WIN+D or similar commands that minimizes the game window. ALT+TAB does not count.

**Comment by goofyseeker311** [comment] 2023-03-17 17:13
well I streamed that on twitch using OBS, so I did WIN defocus the window, so "yes", but it did not go minimized, just out of focus

**Comment by klei1984** [comment] 2023-03-17 17:24
Hmm... then I am not sure, but lets hope that the texture locking issue was the root cause for point 6. which is corrected in commit [c21b38b](https://github.com/klei1984/max/commit/c21b38b243e9d31bc540c50c26d9b8a7be205248).

**Comment by goofyseeker311** [comment] 2023-03-17 17:39
i'll try it soon (having a downloadable release candidate windows build would be fine)

**Comment by klei1984** [comment] 2023-03-17 18:09
github actions creates a windows nsis installer for every build. if you download it, just point the installer to your max installation folder and done. It will overwrite max.ini and maxrun.exe and will copy all DLL dependencies to the same folder. E.g. latest build artifacts (windows nsis installer, linux deb file): https://github.com/klei1984/max/suites/11638844465/artifacts/604201521

**Comment by klei1984** [comment] 2023-03-17 18:13
drats... this was not the root cause for the extreme slowdown. It happened again... I left 3 computers to fight each other in a computer only game and changed focus to another window as you noted. 20 minutes later the game is in slow motion...

**Comment by goofyseeker311** [comment] 2023-03-17 19:15
well, the whole game crashed in 4-cpu turn based mode, after a successful real-time 4-cpu run with no slow downs.
and my fade to black issue appeared when I was gaming in no-turn-time limit turn based mode. wonder what that is.

**Comment by klei1984** [comment] 2023-03-17 23:09
Unfortunately there is no built in crash reporter. If you bump into a recurring crash, please drag and drop attach your SAVE10.DTA file to a new comment. It helps a lot in root cause analysis.

There are two timers. The turn timer represents the time available for the player to take a turn. When the timer reaches 0, the player's turn ends. The end turn timer is the time that computer players have to take their turn. In simultaneous turns based games as soon as one player ends the turn the others have to finish within the end turn timer time.

**Comment by goofyseeker311** [comment] 2023-03-17 23:13
I meant some other internal timer, btw, not game play logic timer

**Comment by klei1984** [comment] 2023-03-18 19:01
Hello @goofyseeker311 , 

> game crashed when starting a 4-cpu turn based fight, after a successful real-time 4-cpu run with no slow downs.

This is fixed in the latest GitHub Actions build. The root causes are documented on the defects page as defect 162 and 163.

**Comment by goofyseeker311** [comment] 2023-03-18 22:07
well the game does not seem to crash, or even slow down, it did that after I saved once, so saving might be the complications trigger.

**Comment by klei1984** [comment] 2023-03-19 20:15
For point 6 this is the root cause analysis result:

When the issue occurs, the GPU load increases from 10-15% to ~40%.
The CPU and other I/O usage does not change at all.

![image](https://user-images.githubusercontent.com/53688147/226190219-3e999e8f-3898-4d39-9434-faa014772ae3.png)

The fading algorithm that is active when the file menu is opened or closed calls `SDL_SetPaletteColors()` 256 times for the full palette and renders the screen at 60 FPS.  The FPS limit is calculated from system time received from `SDL_GetTicks()`.

On the file menu screen the GPU goes to throttling 99% load. The FLIC animation, our floating brain in the jar, is supposed to be rendered at 15 FPS according to the FLIC file parameters, but it is rendered at insane FPS instead even though the system time received from `SDL_GetTicks()` should limit the frame rate to 80 milliseconds between frames minimum or 12.5 FPS maximum.

The `SDL_GetTicks()` interface returns unsigned int (32 bits resolution). The timer starts ticking from 0 at the start of the game executable and normally would roll over after like 49 days. After the issue was identified, the ticker value got sampled at a value of 651'321'397 which is far away from the overflow limit. The particular value corresponds to 9-10 minutes.

The above two observations could indicate a timer issue. In a followup test session a performance timer was installed within the FLIC animation FPS limiter which measured 79.9 milliseconds between two entries into the block body of the FLIC animation handler. After the issue occurred, the performance timer measured 5-600 microseconds between two entries into the same block body which confirms the assumption that the timer is wrong. The tick timer sampled shortly after detection of the issue had a value that corresponds to < 1 minute. This indicates that the tick timer overflows and its value is truncated and compared against a reference value that is not affected by the truncation.

The game simulates the MS-DOS DPMI server's timer interrupt which runs on the system configurable hardware PIT timer. The DOS timer is configured to run at a frequency of 1.19318 MHz or at a rate of 105/88 microseconds. On Windows SDL uses a performance query timer which has better than kHz resolution. That timer resource is used by `SDL_GetTicks()` to provide a millisecond resolution "accurate" time source for applications. The game converts the SDL millisecond timer back to MS-DOS ticks and the simulated GNW Timer API function returns the result as a 32 bit unsigned value. Formula: sdl_ticks * 1000 * 105 / 88. This means that the 49 days that could be represented by the 32 bit unsigned SDL timer is boundary limited to 2^32 / (1000 * 105 / 88) = ~1 hour.

The GNW API functions `timer_get_stamp32()` and `timer_elapsed_time_ms()` are affected in typical use cases.

Example:
```
// call site with elapsed application time > 1 hour.

// time stamp overflows and the value is truncated.
uint32 time_stamp = timer_get_stamp32();
// truncated reference value is passed to GNW API
timer_elapsed_time_ms(time_stamp);

// implementation of timer_elapsed_time_ms()
unsigned int timer_elapsed_time_ms(unsigned int time_stamp) {
    unsigned int result;
    // truncated time_stamp input argument is converted to milliseconds
    unsigned int time_stamp_ms = TIMER_TICKS_TO_MS(time_stamp);
    // non truncated, proper time is fetched in milliseconds
    unsigned int time_ms = SDL_GetTicks();

    // time_ms is guaranteed to be bigger, waaay bigger than truncated time_stamp_ms.
    if (time_ms > time_stamp_ms) {
        result = time_ms - time_stamp_ms;
    } else {
        result = 0uL;
    }

    // result is a huge number after 1 hour of game play.
    return result;
}
```

Remaining open questions:
- So far it was assumed that the occurrence rate of this issue is much faster than 1 hour. If that is true, the above finding is not the root cause.
- How to fix the issue without breaking API compatibility which would need throughout regression testing of 136 call sites.

**Comment by goofyseeker311** [comment] 2023-03-19 20:29
well it takes a lot of time to get the effect, like at least 10min to 30mins, ie, a long full game (turn based 100 turns etc or 4-cpu fight for 30mins or so)

**Comment by goofyseeker311** [comment] 2023-03-19 23:56
hard crash with the new version (ea5ac85) after 10-15min game play.
[SAVE10.dta.zip](https://github.com/klei1984/max/files/11012611/SAVE10.dta.zip)

**Comment by klei1984** [comment] 2023-03-20 07:31
> so the timer is from the starting of the game program, not only timer from the beginning of a game.

Yes, very good observation. You are right, actually the SDL timer starts ticking from 0 on program start and not on game start. And this gives an explanation for the last open question. If you start the program, finish a game in 55 minutes, the next game will break after just 5 minutes. I will do further stress tests, but I am convinced that the fading issue is resolved.

**Comment by goofyseeker311** [comment] 2023-03-20 15:12
one additional error/assert with the newest version (64e329b), as image attached. some task manager assert error.

![max-master-64e329b-assert-error](https://user-images.githubusercontent.com/19920254/226383932-a9bb94a4-dc81-4f03-a03f-020f67557925.jpg)

**Comment by klei1984** [comment] 2023-03-20 16:15
> the video recording of the main menu image, the image only updates up to the mouse cursor, and fully only after mouse is moved.

Thanks for the hints. This seems to be an SDL2 multi monitor setup related behavior. I was able to reproduce it. So far the game was configured to run centered which may have assumed that it should be centered not on the primary monitor only... I do not know.

The latest build adds a max.ini option to select the monitor and the game window is created centered on that display. The game will also do auto aspect ratio matching to the selected display while another new option called disable_ar_correction is set to 0.

These two options eliminated the anomaly of partial re-rendering based on mouse vertical position on my setup. Hope it resolves the anomalies on your system too.

**Comment by klei1984** [comment] 2023-03-20 16:18
Do you have the saved game file for the assertion error case? Maybe that is reproducible.

**Comment by klei1984** [comment] 2023-03-20 16:22
if multiple turns elapsed since then, than it would not be useful for analysis. I will try to set up a game on the same map.

**Comment by goofyseeker311** [comment] 2023-03-20 16:23
yes now its turn 31, and it happened at like turn 5, very early

**Comment by goofyseeker311** [comment] 2023-03-20 16:38
no the new version (00b2f15) did not fix the main menu image problem (main screen still works as normal, the obs capture of the same window is bugged)

**Comment by klei1984** [comment] 2023-03-20 17:10
> the obs capture of the same application window is bugged
Please paste in your [GRAPHICS_SETTINGS] max.ini section.

> is the main menu meant to be 4:3
Yes. No wide screen assets are available. The in-game wide screen GUI elements are dynamically created by the game on the fly. The added value of doing the same for menus compared to required effort to program them is too small. The limited development time and resources are better spent elsewhere.

> main game play view port side bars meant to be so thick (gray bars in the view port)
Tactical map dimensions mast be multiples of 64x64 pixels. Architectural design constraint of drawmap module at minimum zoom level. At maximum zoom level 112 tiles must fit on vertical axis. The gray bars are the reminder between rescaled GUI panels on left and right and the number of 64x64 tiles that fit inbetween. This is basically point 4 from previous discussions.

**Comment by goofyseeker311** [comment] 2023-03-20 17:13
I have default settings. from wherever they came. did not touch them. as none should have to.

[GRAPHICS_SETTINGS]
display_index=0
screen_mode=2
disable_ar_correction=0
scale_quality=1
window_width=640
window_height=480
dialog_center_mode=0

**Comment by klei1984** [comment] 2023-03-20 17:32
> as none should have to.

There is no possibility to configure 11 new settings from in-game.

> I have default settings.
You settings mean that the game:
- creates a borderless window covering your entire primary monitor display using the original display resolution, pixel format and refresh rate.
- the logical screen rendering size is 640x480 pixels only, overridden to 853x480 by disable_ar_correction=0. That 853x480 pixel surface is rescaled to your primary display resolution by SDL2's preferred renderer engine. The renderer engine is auto selected by SDL2.

Options you could try to change and check whether OBS behavior differs:
- change display_index to your other display. E.g. if you have 3 displays, they will have indices: 0,1,2.
- change screen_mode to 1. That creates a fullscreen application instead of a borderless one. The display on which the window is created is exclusive to the game.
- scale quality: it may or may not have any connection. Try out all 3 options, maybe OBS likes one of them: 0,1,2.

General recommendation for screen_mode=2: In this mode your screen remains 4K. The window_width and window_height defines the logical or virtual resolution of the game. Now the game is rendered on 853x480 resolution and you see just a small part of the tactical map at maximum zoom level (closest). Change the logical resolution to 1920x1080. You will see much more of the map.

Recommendation for screen_mode=1: This mode changes your display's resolution and pixel format. Still it worth to try it out as this might make OBS work with SDL2 as expected.

**Comment by goofyseeker311** [comment] 2023-03-20 17:35
um most games work just fine with borderless, so I prefer that to exclusive full screen. in any case.

**Comment by goofyseeker311** [comment] 2023-03-20 18:05
this is mostly fine :) for now

**Comment by klei1984** [comment] 2023-03-20 18:49
In mode 0 the display mode is not changed. Alt+tab and similar are fast. The mouse pointer is grabbed by the game window as soon as it is the active or top most window or the mouse hovers over any small part of it. If the window size is proportional to the full display or desktop the mouse is semi guaranteed to be locked in most use case. If mouse grab is disabled in windowed mode the in-game mouse pointer gets desynchronized to the physical mouse position due to relative mouse mode which is required for the game engine for now. This mouse pointer desynch is very annoying according to various user feedback.

In mode 1 the game changes OS display modes at every alt tab or similar loss of focus. SDL2 seems to handle this very slow.

In mode 2 there is no display mode switch and mouse grab seems to work a bit differently, relaxed. SDL2 mouse handling mode is not different though.

what happens if you set display_index=1 ?

On my Windows PC SDL2 supports 6 render drivers: Direct3D, Direct3D11, Direct3D12, OpenGL, OpenGL-ES2, GLES Software. The "best" selected by SDL2 automatically is Direct3D. Interesting...

Maybe OBS would work better with other renderers... problem is that there is no way to tell which renderers are available on a computer and configuring by index will give back different results on different computers. A sophisticated implementation may try to compare renderer names with ini settings but that is implementation defined and SDL can change the names or supported drivers at any time :(

**Comment by goofyseeker311** [comment] 2023-03-20 18:52
doesnt SDL provide the API interfaces to switch whatever

**Comment by klei1984** [comment] 2023-03-20 19:04
> and the window grabs the mouse even if its not selected/clicked

It is enough if the window becomes topmost or when the mouse pointer hovers over the game window (click, select not needed).

> display_index=1

Ah, of course... I did not think that through.

> SDL definitely was not designed to work slowly on those operations

The game itself does not handle any window related events. What we observe is 100% SDL2.

I will try to install this OBS thingy and try to reproduce the issue.

**Comment by goofyseeker311** [comment] 2023-03-20 19:06
well in multimonitor setup, the mode=1 seems to be topmost all the time, no matter if you try to click to other screen windows

**Comment by goofyseeker311** [comment] 2023-03-20 19:33
added you in discord for later use.

**Comment by klei1984** [comment] 2023-03-20 21:03
The fade to black is resolved on latest master.

**Closed by klei1984** 2023-03-20 21:03 UTC
Labels: bug

**Comment by goofyseeker311** [comment] 2023-03-20 21:05
sorry to see you to be work pride ridden. here is some more defects to solve.

![maxassertfinal](https://user-images.githubusercontent.com/19920254/226465718-eb53f3e9-2291-44b9-a694-5998f5eacff5.jpg)
[SAVE10c-dta.zip](https://github.com/klei1984/max/files/11023046/SAVE10c-dta.zip)

**Comment by goofyseeker311** [comment] 2023-03-20 22:19
https://hex-rays.com/ida-free/ or any similar ASM86-to-ANSIC converter, if you dont mind

**Comment by goofyseeker311** [comment] 2023-03-29 08:21
well another crash midgame with 4-cpu. attached is the save file.

[SAVE10d.dta.zip](https://github.com/klei1984/max/files/11098146/SAVE10d.dta.zip)

**Comment by goofyseeker311** [comment] 2023-04-27 22:16
hope things are going well.

anyways, tried the latest version ([e91c4a6](https://github.com/klei1984/max/commit/e91c4a67bd2577cd373b47fa7dbdc21897f4a76f))
with default 4K graphics settings, it will crash-flat if you win-key/alt-tab during the slowed down loading start screen.

**Comment by segatrade** [comment] 2023-04-28 09:12
> anyways, tried the latest version ([e91c4a6](https://github.com/klei1984/max/commit/e91c4a67bd2577cd373b47fa7dbdc21897f4a76f)) with default 4K graphics settings, it will crash-flat if you win-key/alt-tab during the slowed down loading start screen.

4k issue: https://github.com/klei1984/max/issues/24

**Comment by goofyseeker311** [comment] 2023-04-30 13:43
generally 4K refresh rate is slow, for no apparent reason. in normal game too.

**Comment by goofyseeker311** [comment] 2023-05-01 21:30
still crashing very frequently 4-cpu versus fight (version 02256d1). attached is the save file.

[SAVE10-02256d1.dta.zip](https://github.com/klei1984/max/files/11368157/SAVE10-02256d1.dta.zip)

**Comment by goofyseeker311** [comment] 2023-05-04 18:34
newest version still crashing very often in same way straight to desktop (45e1154). attached the log data save file.

[SAVE10-45e1154.dta.zip](https://github.com/klei1984/max/files/11400362/SAVE10-45e1154.dta.zip)

**Comment by goofyseeker311** [comment] 2023-05-07 07:30
here is a similar crash in the latest version (638f21c)

[SAVE10-638f21c.dta.zip](https://github.com/klei1984/max/files/11414188/SAVE10-638f21c.dta.zip)

**Comment by goofyseeker311** [comment] 2023-05-13 14:37
0.4.1 seems stable so far, but one issue, when the window is not selected/foreground, ie alt-tab/win-key out, then it will slow to a very low fps, even if not wanted, 1st game finish no crash btw

**Comment by goofyseeker311** [comment] 2023-05-13 19:51
in v0.4.1 this error message appeared, after several full fights, and after pressing ignore a couple times everything ai stopped.

![debug2](https://github.com/klei1984/max/assets/19920254/75fd6d60-0982-4851-8ea0-a6ccfa40c34d)

**Comment by goofyseeker311** [comment] 2023-07-10 02:39
well, 4K does not launch at all now.

**Comment by goofyseeker311** [comment] 2023-08-18 18:45
turn lock at turn 8, default settings. older c1bef0e version.
![debug2](https://github.com/klei1984/max/assets/19920254/e44b2d6f-2e14-442d-b3d5-fe17189ed0be)

[SAVE10-c1bef0e.zip](https://github.com/klei1984/max/files/12383192/SAVE10-c1bef0e.zip)

**Comment by goofyseeker311** [comment] 2023-08-18 19:36
same turn end lockup, latest version 1ae878f, default install settings.

![debug3](https://github.com/klei1984/max/assets/19920254/ed9f722f-f143-4f8d-96e0-cec01cc541f9)
![debug4](https://github.com/klei1984/max/assets/19920254/ce6277c1-6275-4b63-8005-10d559066fab)

[SAVE10-1ae878f.DTA.zip](https://github.com/klei1984/max/files/12383517/SAVE10-1ae878f.DTA.zip)

**Comment by goofyseeker311** [comment] 2023-09-04 06:38
still the same turn time at 00:00 lockup issue.

![debug6](https://github.com/klei1984/max/assets/19920254/bad50929-fd04-43dc-a7ee-fd96322d90a4)
[SAVE10-d0fc104.dta.zip](https://github.com/klei1984/max/files/12510009/SAVE10-d0fc104.dta.zip)

**Comment by goofyseeker311** [comment] 2023-09-07 12:56
nope, still 00:00 turn jam (and some random crash to desktop, dont know why).

[SAVE10-eda329e.dta.zip](https://github.com/klei1984/max/files/12549324/SAVE10-eda329e.dta.zip)

**Comment by goofyseeker311** [comment] 2023-09-08 06:32
still 00:00 turn jam. I think the save10.dta log stops also when the jam happens.

[SAVE10-e775450.dta.zip](https://github.com/klei1984/max/files/12556237/SAVE10-e775450.dta.zip)

**Comment by goofyseeker311** [comment] 2023-09-09 09:20
nope: 
[SAVE10-5fca1e9.dta.zip](https://github.com/klei1984/max/files/12565388/SAVE10-5fca1e9.dta.zip)

**Comment by goofyseeker311** [comment] 2023-09-09 16:44
[SAVE10-1f6fd36.dta.zip](https://github.com/klei1984/max/files/12566262/SAVE10-1f6fd36.dta.zip)

**Comment by goofyseeker311** [comment] 2023-09-12 12:46
seems not to crash/jam in the 00:00 turn timer anymore. but seems like if you sit in a game completion score screen for long time, and then press the ok button. it will crash out of the game directly. the game save10.dta file might will not contain the crash reason, it only recorded up to the end of the game to the score screen and stopped there.

[SAVE10-28d547b.dta.zip](https://github.com/klei1984/max/files/12586490/SAVE10-28d547b.dta.zip)

**Comment by goofyseeker311** [comment] 2023-09-14 18:17
surveyors on auto will get stuck in map pouches.

**Comment by goofyseeker311** [comment] 2023-09-16 16:59
failed compile tho.

**Comment by goofyseeker311** [comment] 2023-09-18 17:58
sometimes new game crashes, idk if it has something to do with timings/waiting desync or something.

**Comment by goofyseeker311** [comment] 2023-09-18 20:08
ok caught the after score in game crash: 
[SAVE10-b9b45b6-2.dta.zip](https://github.com/klei1984/max/files/12653051/SAVE10-b9b45b6-2.dta.zip)

**Comment by goofyseeker311** [comment] 2023-09-20 12:56
well it still crashes right after a new game after a successfully ended game, sometimes.

**Comment by goofyseeker311** [comment] 2023-09-25 11:23
this kind of crash to desktop: [SAVE10-458661c.dta.zip](https://github.com/klei1984/max/files/12714453/SAVE10-458661c.dta.zip)

**Comment by goofyseeker311** [comment] 2023-09-30 01:26
this kind of crash to desktop after 2-3 successful skirmish game runs.
[SAVE10-8f2ba6a.dta.zip](https://github.com/klei1984/max/files/12773132/SAVE10-8f2ba6a.dta.zip)

**Comment by goofyseeker311** [comment] 2023-10-01 19:07
this time it took many games like 10 to crash, and it crashed right after pressing the start game button (the one after all the game settings, 4-cpu mode).

[SAVE10-96af8c4.DTA.zip](https://github.com/klei1984/max/files/12777989/SAVE10-96af8c4.DTA.zip)

**Comment by goofyseeker311** [comment] 2023-10-01 22:57
this kind of long game error: 
[SAVE10-96af8c4.zip](https://github.com/klei1984/max/files/12778434/SAVE10-96af8c4.zip)
![debug7](https://github.com/klei1984/max/assets/19920254/c4b34c72-0eb8-4377-b64c-f1abdb049bda)

**Comment by goofyseeker311** [comment] 2023-10-02 01:52
at turn 333, the small power plant image keeps popping up in its place, no matter if the turn ends, like its being constructed all the time.

**Comment by goofyseeker311** [comment] 2023-10-02 02:20
this kind of crash to desktop: 
[SAVE10-96af8c4-2.DTA.zip](https://github.com/klei1984/max/files/12779130/SAVE10-96af8c4-2.DTA.zip)

**Comment by goofyseeker311** [comment] 2023-10-08 02:04
this kind of direct game start crash to desktop, a second after a few seconds of a start, same crash the third try:
[SAVE10-86ef552.DTA.zip](https://github.com/klei1984/max/files/12839581/SAVE10-86ef552.DTA.zip)
[SAVE10-86ef552-2.DTA.zip](https://github.com/klei1984/max/files/12839584/SAVE10-86ef552-2.DTA.zip)

**Comment by goofyseeker311** [comment] 2023-10-13 20:54
now it will not crash right at the start, but the usual 00:00 turn time jam is still there.
[SAVE10-7306e62.DTA.zip](https://github.com/klei1984/max/files/12899151/SAVE10-7306e62.DTA.zip)

**Comment by goofyseeker311** [comment] 2023-10-20 13:02
crashing right after an ended game, when starting a new game 4-cpu. all sounds were muted.
[SAVE10-0.6.0.DTA.zip](https://github.com/klei1984/max/files/13054505/SAVE10-0.6.0.DTA.zip)

**Comment by goofyseeker311** [comment] 2023-10-28 21:07
white busy jam crash at turn timer 00:40. 
[SAVE10-4d22674.DTA.zip](https://github.com/klei1984/max/files/13196722/SAVE10-4d22674.DTA.zip)

**Comment by goofyseeker311** [comment] 2023-11-01 16:27
middle of game crash to desktop: 
[SAVE10-b068279.DTA.zip](https://github.com/klei1984/max/files/13229339/SAVE10-b068279.DTA.zip)

**Comment by goofyseeker311** [comment] 2023-11-12 00:42
the game still crashes at a new game start, randomly, just before any turns or units are seen. no SAVE10.DATA written.
